package vistas;

import modelo.PersonalDAO;
import modelo.Personal;
import java.util.List;
import javax.swing.JOptionPane;
import java.sql.*;

import modelo.conexion;

public class Login extends javax.swing.JFrame {

    private String usuario;
    private String password;

    public static Personal personalLogeado;
    public static Personal tipoPersonal;
    public static int indice = 0;

    public Login() {
        initComponents();
   TransparenciaBoton();
       
        jlblOjo.setVisible(true);
        jlblOjoTachado.setVisible(false);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Login - VETERINARIA SAN MARTIN");
    }
    public void TransparenciaBoton() {
        jButton1.setOpaque(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setBorderPainted(false);
    }
    private Personal LogDatosPers(Personal personal) {
        Personal personalLog;
        int idPerso = personal.getIdPerso();
        String nombre = personal.getNomPerso();
        String apellido = personal.getApePerso();
        String dni = personal.getDniPerso();
        String direccion = personal.getDirecPerso();
        String email = personal.getEmailPerso();
        String telefono = personal.getFonoPerso();
        String user = personal.getUsuPerso();
        String pass = personal.getPassPerso();

        personalLog = new Personal(idPerso, nombre, apellido, dni, direccion, email, telefono, user, pass);
        return personalLog;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtContra = new javax.swing.JPasswordField();
        jlblOjo = new javax.swing.JLabel();
        jlblOjoTachado = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user1.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 130, 140));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LOGIN1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 160, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("VETERINARIA - SAN MARTIN");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/dog sitting.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lying cat.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 300, 360));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user2.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, 30));

        jtxtUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUsuarioActionPerformed(evt);
            }
        });
        jtxtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtUsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 140, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/password.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, 40));

        jtxtContra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtContra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtContraKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 140, 30));

        jlblOjo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/OJO.png"))); // NOI18N
        jlblOjo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlblOjo.setMaximumSize(new java.awt.Dimension(20, 22));
        jlblOjo.setMinimumSize(new java.awt.Dimension(20, 22));
        jlblOjo.setPreferredSize(new java.awt.Dimension(20, 22));
        jlblOjo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblOjoMouseClicked(evt);
            }
        });
        getContentPane().add(jlblOjo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 26, 24));

        jlblOjoTachado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/OJO TACHADO.png"))); // NOI18N
        jlblOjoTachado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlblOjoTachado.setMaximumSize(new java.awt.Dimension(24, 26));
        jlblOjoTachado.setMinimumSize(new java.awt.Dimension(24, 26));
        jlblOjoTachado.setPreferredSize(new java.awt.Dimension(24, 26));
        jlblOjoTachado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblOjoTachadoMouseClicked(evt);
            }
        });
        getContentPane().add(jlblOjoTachado, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Rectangle 35.png"))); // NOI18N
        jLabel8.setAlignmentY(0.0F);
        jLabel8.setAutoscrolls(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 250, 380));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Thumbnail.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 520));

        setBounds(0, 0, 816, 552);
    }// </editor-fold>//GEN-END:initComponents

    private void jlblOjoTachadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblOjoTachadoMouseClicked
        jtxtContra.setEchoChar('*');
        jlblOjo.setVisible(true);
        jlblOjoTachado.setVisible(false);
    }//GEN-LAST:event_jlblOjoTachadoMouseClicked

    private void jlblOjoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblOjoMouseClicked
        jtxtContra.setEchoChar((char) 0);
        jlblOjo.setVisible(false);
        jlblOjoTachado.setVisible(true);
    }//GEN-LAST:event_jlblOjoMouseClicked

    private void jtxtContraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtContraKeyPressed
//METODO U ACCION PARA QUE AL DAR ENTER INICIE SESION
        if (evt.getKeyCode() == evt.VK_ENTER) {
            this.Login();
        }
    }//GEN-LAST:event_jtxtContraKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.Login();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed

    }//GEN-LAST:event_jButton1KeyPressed

    private void jtxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtUsuarioActionPerformed

    private void jtxtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtUsuarioKeyPressed
        //METODO U ACCION PARA QUE AL DAR ENTER CAMBIE DE CAMPO DE INGRESO DE DATOS
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jtxtContra.requestFocus();
        }
    }//GEN-LAST:event_jtxtUsuarioKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jlblOjo;
    private javax.swing.JLabel jlblOjoTachado;
    private javax.swing.JPasswordField jtxtContra;
    private javax.swing.JTextField jtxtUsuario;
    // End of variables declaration//GEN-END:variables
//metodo Iniciar Sesion
    private void Login() {
        String user = jtxtUsuario.getText();
        String pass = String.valueOf(jtxtContra.getPassword());

        String url = "select USU_PERSO, PASS_PERSO, ID_TIPOPER "
                + "from personal where USU_PERSO='" + user + "'";
        try {
            Connection con = conexion.conectar();
            PreparedStatement ps = con.prepareStatement(url);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                //SI EXISTE EL USUARIO
                String u = rs.getString("USU_PERSO");
                String p = rs.getString("PASS_PERSO");
                String i = rs.getString("ID_TIPOPER");
                if (pass.equals(p)) {
                    //VAMOS A EMPLEADO O ADMIN
                    if (i.equals("1")) {
                        PersonalDAO personaldao = new PersonalDAO();
                        List<Personal> personales = personaldao.seleccionar();
                        boolean bandera = false;
                        for (Personal personalLogin : personales) {
                            if (u.equalsIgnoreCase(personalLogin.getUsuPerso()) && p.equalsIgnoreCase(personalLogin.getPassPerso())) {
                                tipoPersonal = personalLogin;
                                personalLogeado = LogDatosPers(personalLogin);
                                Principal principal = new Principal();
                                principal.setVisible(true);
                                bandera = true;
                                this.dispose();
                            }
                        }
                    } else if (i.equals("2")) {
                        PersonalDAO personaldao = new PersonalDAO();
                        List<Personal> personales = personaldao.seleccionar();
                        boolean bandera = false;
                        for (Personal personalLogin : personales) {
                            if (u.equalsIgnoreCase(personalLogin.getUsuPerso()) && p.equalsIgnoreCase(personalLogin.getPassPerso())) {
                                tipoPersonal = personalLogin;
                                personalLogeado = LogDatosPers(personalLogin);
                                Principal_Empleado principal2 = new Principal_Empleado();
                                principal2.setVisible(true);
                                bandera = true;
                                this.dispose();
                            }
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "LA CONTRASEÑA NO ES CORRECTA");
                }
            } else {
                //EL USUARIO NO EXISTE
                JOptionPane.showMessageDialog(null, "EL USUARIO NO EXISTE");
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }
}
