/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelo.Servicios;
import modelo.ServiciosDAO;

public class ServiciosForm extends javax.swing.JInternalFrame {

    ServiciosDAO serdao = new ServiciosDAO();
    Servicios ser = new Servicios();
    DefaultTableModel modelo = new DefaultTableModel();
    TableRowSorter trs;
    int id;
    double precio;

    public ServiciosForm() {
        initComponents();
        TransparenciaBoton();
        Listar();
        DesactivarBoton();
    }

    private void ActivarBoton() {
        btnEliminar.setEnabled(true);
        btnActualizar.setEnabled(true);
    }

    private void DesactivarBoton() {
        btnEliminar.setEnabled(false);
        btnActualizar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPrecio = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtBuscarservicio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        btnNuevo1 = new javax.swing.JButton();
        btnAgregar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("REGISTRAR SERVICIOS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPrecio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 144, -1));

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BOTON MODIFICAR.png"))); // NOI18N
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 226, 149, 60));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BOTON ELIMINAR.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 225, 150, 60));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("TIPO DE MASCOTA:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 30));

        txtBuscarservicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBuscarservicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarservicioActionPerformed(evt);
            }
        });
        txtBuscarservicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarservicioKeyTyped(evt);
            }
        });
        getContentPane().add(txtBuscarservicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 282, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("DESCRIPCIÓN:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("DATOS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 70, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("PRECIO:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 30));

        txtDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyTyped(evt);
            }
        });
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 144, -1));

        txtTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTipoKeyTyped(evt);
            }
        });
        getContentPane().add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 144, -1));

        btnNuevo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BOTON NUEVO.png"))); // NOI18N
        btnNuevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevo1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 226, 140, 60));

        btnAgregar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BOTON REGISTRAR.png"))); // NOI18N
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 226, 160, 60));

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Tabla.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DESCRIPCIÓN", "PRECIO", "ID_TIPO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);
        if (Tabla.getColumnModel().getColumnCount() > 0) {
            Tabla.getColumnModel().getColumn(0).setResizable(false);
            Tabla.getColumnModel().getColumn(0).setPreferredWidth(15);
            Tabla.getColumnModel().getColumn(1).setResizable(false);
            Tabla.getColumnModel().getColumn(1).setPreferredWidth(100);
            Tabla.getColumnModel().getColumn(2).setResizable(false);
            Tabla.getColumnModel().getColumn(2).setPreferredWidth(30);
            Tabla.getColumnModel().getColumn(3).setResizable(false);
            Tabla.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 429, 180));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("BUSCAR SERVICIO:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 7, -1, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo1.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 810, 310));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BOTON NUEVO.png"))); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 252, 129, 34));

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BOTON REGISTRAR.png"))); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 252, 141, 34));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void TransparenciaBoton() {
        btnActualizar.setOpaque(false);
        btnActualizar.setContentAreaFilled(false);
        btnActualizar.setBorderPainted(false);
        btnEliminar.setOpaque(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setBorderPainted(false);
        btnNuevo1.setOpaque(false);
        btnNuevo1.setContentAreaFilled(false);
        btnNuevo1.setBorderPainted(false);
        btnAgregar1.setOpaque(false);
        btnAgregar1.setContentAreaFilled(false);
        btnAgregar1.setOpaque(false);
    }
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        eliminar();
        limpiarTabla();
        Listar();
        nuevo();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        actualizar();
        limpiarTabla();
        Listar();
        nuevo();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        agregar();
        limpiarTabla();
        Listar();
        nuevo();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        nuevo();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void txtBuscarservicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarservicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarservicioActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // TODO add your handling code here:
        int fila = Tabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        } else {
            id = Integer.parseInt(Tabla.getValueAt(fila, 0).toString());
            String descripcion = Tabla.getValueAt(fila, 1).toString();
            String precio = Tabla.getValueAt(fila, 2).toString();
            String id_tipo = Tabla.getValueAt(fila, 3).toString();

            txtDescripcion.setText(descripcion);
            txtPrecio.setText(precio);
            txtTipo.setText(id_tipo);

            ActivarBoton();

        }
    }//GEN-LAST:event_TablaMouseClicked

    private void txtBuscarservicioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarservicioKeyTyped
        // TODO add your handling code here:
        txtBuscarservicio.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent se) {
                trs.setRowFilter(RowFilter.regexFilter("(?i)" + txtBuscarservicio.getText(), 0, 1, 3));

            }

        });
        trs = new TableRowSorter(modelo);
        Tabla.setRowSorter(trs);
    }//GEN-LAST:event_txtBuscarservicioKeyTyped

    private void txtDescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyReleased
        // TODO add your handling code here:
//        txtDescripcion.setText(txtDescripcion.getText().toUpperCase());
    }//GEN-LAST:event_txtDescripcionKeyReleased

    private void txtDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyTyped
        // TODO add your handling code here:
        Character letra = evt.getKeyChar();
        char numero = evt.getKeyChar();

        if (Character.isLetter(letra) || (evt.getKeyChar() == KeyEvent.VK_SPACE)
                || (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE) || (evt.getKeyChar() == KeyEvent.VK_MINUS)
                || !(evt.getKeyChar() == KeyEvent.VK_PAGE_DOWN)) {
            evt.setKeyChar(Character.toUpperCase(letra));
        } else {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }

        if (Character.isDigit(numero)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }

        if (txtDescripcion.getText().length() >= 25) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }

    }//GEN-LAST:event_txtDescripcionKeyTyped

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void txtTipoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTipoKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTipoKeyTyped

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
        // TODO add your handling code here:
        agregar();
        limpiarTabla();
        Listar();
        nuevo();
    }//GEN-LAST:event_btnAgregar1ActionPerformed

    private void btnNuevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevo1ActionPerformed
        // TODO add your handling code here:
        nuevo();
    }//GEN-LAST:event_btnNuevo1ActionPerformed
    void Listar() {
        List<Servicios> lista = serdao.Listar();
        modelo = (DefaultTableModel) this.Tabla.getModel();
        Object[] ob = new Object[4];
        for (int i = 0; i < lista.size(); i++) {
            ob[0] = lista.get(i).getId();
            ob[1] = lista.get(i).getDescripcion();
            ob[2] = lista.get(i).getPrecio();
            ob[3] = lista.get(i).getId_tipo();
            modelo.addRow(ob);
        }
        Tabla.setModel(modelo);
    }

    void eliminar() {
        int fila = Tabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        } else {
            serdao.Eliminar(id);
        }
    }

    void nuevo() {
        txtDescripcion.setText("");
        txtPrecio.setText("");
        txtTipo.setText("");
        txtDescripcion.requestFocus();

    }

    void actualizar() {
        int fila = Tabla.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        } else {
            String descripcion = txtDescripcion.getText();
            precio = Double.parseDouble(txtPrecio.getText());
            String id_tipo = txtTipo.getText();
            modelo = (DefaultTableModel) Tabla.getModel();
            ArrayList lista = new ArrayList();
            if (precio > 0) {
                lista.add(id);
                lista.add(descripcion);
                lista.add(precio);
                lista.add(id_tipo);

                Object[] obj = new Object[4];
                obj[0] = descripcion;
                obj[1] = precio;
                obj[2] = id_tipo;
                obj[3] = id;
                serdao.Actualizar(obj);
                JOptionPane.showMessageDialog(this, "VALOR INGRESADO CON ÉXITO");
            } else {
                JOptionPane.showMessageDialog(this, "EL VALOR INGRESADO NO ES VÁLIDO");
                JOptionPane.showMessageDialog(this, "POR FAVOR INGRESAR UN NUEVO VALOR");
                JOptionPane.showMessageDialog(this, "¡GRACIAS!");
            }
        }
    }

    void agregar() {
        String descripcion = txtDescripcion.getText();
        precio = Double.parseDouble(txtPrecio.getText());
        String id_tipo = txtTipo.getText();
        modelo = (DefaultTableModel) Tabla.getModel();
        ArrayList lista = new ArrayList();
        if (precio > 0) {
            lista.add(id);
            lista.add(descripcion);
            lista.add(precio);
            lista.add(id_tipo);

            Object[] ob = new Object[4];
            ob[0] = descripcion;
            ob[1] = precio;
            ob[2] = id_tipo;
            serdao.add(ob);
            JOptionPane.showMessageDialog(this, "VALOR INGRESADO CON ÉXITO");
        } else {
            JOptionPane.showMessageDialog(this, "EL VALOR INGRESADO NO ES VÁLIDO");
            JOptionPane.showMessageDialog(this, "POR FAVOR INGRESAR UN NUEVO VALOR");
            JOptionPane.showMessageDialog(this, "¡GRACIAS!");
        }
    }

    void limpiarTabla() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnNuevo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscarservicio;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
