package vistas;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import modelo.PersonalDAO;
import modelo.Personal;
import javax.swing.JOptionPane;

public class VentanaDatosPersonales extends javax.swing.JInternalFrame {

    private Personal personalLog = Login.personalLogeado;

    public VentanaDatosPersonales() {
        initComponents();
        TransparenciaBoton();
        MostrarDatos();
    }

    private void MostrarDatos() {
        jtxtNombre.setText(personalLog.getNomPerso());
        jtxtApellidos.setText(personalLog.getApePerso());
        jtxtDNI.setText(personalLog.getDniPerso());
        jtxtDireccion.setText(personalLog.getDirecPerso());
        jtxtEmail.setText(personalLog.getEmailPerso());
        jtxtTelefono.setText(personalLog.getFonoPerso());
        jtxtUsuario.setText(personalLog.getUsuPerso());
        jtxtPassword.setText(personalLog.getPassPerso());
    }

    private Personal RecogerDatos() {

        Personal personal;
        int idPerso = personalLog.getIdPerso();
        String nombre = jtxtNombre.getText();
        String apellido = jtxtApellidos.getText();
        String dni = jtxtDNI.getText();
        String direccion = jtxtDireccion.getText();
        String email = jtxtEmail.getText();
        String telefono = jtxtTelefono.getText();
        String usuario = jtxtUsuario.getText();
        String password = jtxtPassword.getText();

        personal = new Personal(idPerso, nombre, apellido, dni, direccion, email, telefono, usuario, password);

        return personal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblNombre = new javax.swing.JLabel();
        jButton_Modificar = new javax.swing.JButton();
        jtxtNombre = new javax.swing.JTextField();
        jtxtApellidos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtDNI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtDireccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtPassword = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jlblModifique = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtxtTelefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Datos Personales");
        setToolTipText("");
        setMinimumSize(new java.awt.Dimension(375, 630));
        setPreferredSize(new java.awt.Dimension(375, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblNombre.setForeground(new java.awt.Color(0, 0, 0));
        jlblNombre.setText("Nombres");
        getContentPane().add(jlblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, 20));

        jButton_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BOTON MODIFICAR.png"))); // NOI18N
        jButton_Modificar.setBorder(null);
        jButton_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 150, 60));

        jtxtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNombreActionPerformed(evt);
            }
        });
        jtxtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtNombreKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(jtxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 160, 30));

        jtxtApellidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtApellidosKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtApellidosKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtApellidosKeyTyped(evt);
            }
        });
        getContentPane().add(jtxtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 160, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Apellidos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, 20));

        jtxtDNI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtDNIKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtDNIKeyTyped(evt);
            }
        });
        getContentPane().add(jtxtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 160, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("DNI");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, 20));

        jtxtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEmailActionPerformed(evt);
            }
        });
        jtxtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtEmailKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtEmailKeyTyped(evt);
            }
        });
        getContentPane().add(jtxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 160, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, 20));

        jtxtDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtDireccionKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 160, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Dirección");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, 20));

        jtxtUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtUsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 160, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Usuario");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, 20));

        jtxtPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtPasswordKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 160, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, 20));

        jlblModifique.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlblModifique.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlblModifiqueMouseClicked(evt);
            }
        });
        getContentPane().add(jlblModifique, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Telefono");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, 20));

        jtxtTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtxtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtTelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtTelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(jtxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 160, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user1.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 130, 140));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Rectangle 1.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 600));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void TransparenciaBoton() {
        jButton_Modificar.setOpaque(false);
        jButton_Modificar.setContentAreaFilled(false);
        jButton_Modificar.setBorderPainted(false);
    }
    private void jlblModifiqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlblModifiqueMouseClicked

        //Recoger los datos
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea modificar el registro?", "Cambio de Registro", dialog);
        if (result == 0) {
            Personal personal = RecogerDatos();
            PersonalDAO personaldao = new PersonalDAO();
            personaldao.updateDatosPersonales(personal);
            personalLog = Login.personalLogeado = personal;
            MostrarDatos();
        }
    }//GEN-LAST:event_jlblModifiqueMouseClicked

    private void jtxtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombreKeyTyped

    private void jtxtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNombreKeyReleased
        // TODO add your handling code here:
        jtxtNombre.setText(jtxtNombre.getText().toUpperCase());
    }//GEN-LAST:event_jtxtNombreKeyReleased

    private void jtxtApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtApellidosKeyTyped
        // TODO add your handling code here: 
    }//GEN-LAST:event_jtxtApellidosKeyTyped

    private void jtxtApellidosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtApellidosKeyReleased
        // TODO add your handling code here:
        jtxtApellidos.setText(jtxtApellidos.getText().toUpperCase());
    }//GEN-LAST:event_jtxtApellidosKeyReleased

    private void jtxtDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDNIKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDNIKeyTyped

    private void jtxtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTelefonoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTelefonoKeyTyped

    private void jtxtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtEmailKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEmailKeyTyped

    private void jtxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombreActionPerformed

    private void jtxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEmailActionPerformed

    private void jtxtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNombreKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            Character letra = evt.getKeyChar();
            char numero = evt.getKeyChar();
            if (Character.isLetter(letra) || (evt.getKeyChar() == KeyEvent.VK_SPACE)
                    || (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE) || (evt.getKeyChar() == KeyEvent.VK_MINUS)
                    || !(evt.getKeyChar() == KeyEvent.VK_PAGE_DOWN)) {
                evt.setKeyChar(Character.toUpperCase(letra));
            } else {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }

            if (Character.isDigit(numero)) {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }

            if (jtxtNombre.getText().length() >= 25) {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            jtxtApellidos.requestFocus();
        }
    }//GEN-LAST:event_jtxtNombreKeyPressed

    private void jtxtApellidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtApellidosKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            Character letra = evt.getKeyChar();
            char numero = evt.getKeyChar();

            if (Character.isLetter(letra) || (evt.getKeyChar() == KeyEvent.VK_SPACE)
                    || (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE) || (evt.getKeyChar() == KeyEvent.VK_MINUS)
                    || !(evt.getKeyChar() == KeyEvent.VK_PAGE_DOWN)) {
                evt.setKeyChar(Character.toUpperCase(letra));
            } else {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }

            if (Character.isDigit(numero)) {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }

            if (jtxtApellidos.getText().length() >= 25) {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            jtxtDNI.requestFocus();
        }
    }//GEN-LAST:event_jtxtApellidosKeyPressed

    private void jtxtDNIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDNIKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            int key = evt.getKeyChar();
            boolean numeros = key >= 48 && key <= 57;
            if (!numeros) {
                evt.consume();
            }
//EL 8 ES LA CANTIDAD MAX. DE CARÁCTERES PERMITIDOS
            if (jtxtDNI.getText().trim().length() == 8) {
                evt.consume();
            }
            jtxtEmail.requestFocus();
        }
    }//GEN-LAST:event_jtxtDNIKeyPressed

    private void jtxtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtEmailKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            Character letra = evt.getKeyChar();
            char numero = evt.getKeyChar();

            if (Character.isLetter(letra) || (evt.getKeyChar() == KeyEvent.VK_SPACE)
                    || (evt.getKeyChar() == KeyEvent.VK_BACK_SPACE) || (evt.getKeyChar() == KeyEvent.VK_MINUS)
                    || !(evt.getKeyChar() == KeyEvent.VK_PAGE_DOWN)) {
                evt.setKeyChar(Character.toUpperCase(letra));
            } else {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }

            if (Character.isDigit(numero)) {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }

            if (jtxtEmail.getText().length() >= 25) {
                evt.consume();
                Toolkit.getDefaultToolkit().beep();
            }
            jtxtDireccion.requestFocus();
        }
    }//GEN-LAST:event_jtxtEmailKeyPressed

    private void jtxtDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDireccionKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jtxtTelefono.requestFocus();
        }
    }//GEN-LAST:event_jtxtDireccionKeyPressed

    private void jtxtTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTelefonoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            int key = evt.getKeyChar();
            boolean numeros = key >= 48 && key <= 57;
            if (!numeros) {
                evt.consume();
            }
//EL 9 ES LA CANTIDAD MAX. DE CARÁCTERES PERMITIDOS
            if (jtxtTelefono.getText().trim().length() == 9) {
                evt.consume();
            }
            jtxtUsuario.requestFocus();
        }
    }//GEN-LAST:event_jtxtTelefonoKeyPressed

    private void jtxtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtUsuarioKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            jtxtPassword.requestFocus();
        }
    }//GEN-LAST:event_jtxtUsuarioKeyPressed

    private void jtxtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPasswordKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            this.Modifique();
        }
    }//GEN-LAST:event_jtxtPasswordKeyPressed

    private void jButton_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ModificarActionPerformed
        this.Modifique();
    }//GEN-LAST:event_jButton_ModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Modificar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlblModifique;
    private javax.swing.JLabel jlblNombre;
    private javax.swing.JTextField jtxtApellidos;
    private javax.swing.JTextField jtxtDNI;
    private javax.swing.JTextField jtxtDireccion;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtPassword;
    private javax.swing.JTextField jtxtTelefono;
    private javax.swing.JTextField jtxtUsuario;
    // End of variables declaration//GEN-END:variables
private void Modifique() {
        //Recoger los datos
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "¿Desea modificar el registro?", "Cambio de Registro", dialog);
        if (result == 0) {
            Personal personal = RecogerDatos();
            PersonalDAO personaldao = new PersonalDAO();
            personaldao.updateDatosPersonales(personal);
            personalLog = Login.personalLogeado = personal;
            MostrarDatos();
        }
    }
}
